import type { Usuario, Auditoria, PlanDeAccion, ActividadSeguimiento, Criticidad, EstadoCumplimiento } from "./types"

export const usuarios: Usuario[] = [
  {
    id: "1",
    nombre: "María González",
    email: "maria.gonzalez@correosChile.cl",
    rol: "gerencia",
    gerencia: "Operaciones",
  },
  {
    id: "2",
    nombre: "Carlos Rodríguez",
    email: "carlos.rodriguez@correosChile.cl",
    rol: "gerencia",
    gerencia: "Finanzas",
  },
  { id: "3", nombre: "Ana Martínez", email: "ana.martinez@correosChile.cl", rol: "auditor" },
  { id: "4", nombre: "Pedro Silva", email: "pedro.silva@correosChile.cl", rol: "auditor" },
  { id: "5", nombre: "Roberto Fernández", email: "roberto.fernandez@correosChile.cl", rol: "comite" },
  { id: "6", nombre: "Laura Soto", email: "laura.soto@correosChile.cl", rol: "gerencia", gerencia: "Tecnología" },
  { id: "7", nombre: "Juan Pérez", email: "juan.perez@correosChile.cl", rol: "gerencia", gerencia: "Recursos Humanos" },
]

export const auditorias: Auditoria[] = [
  {
    id: "AUD-001",
    nombre: "Auditoría de Procesos Operativos 2024",
    fecha: "2024-03-15",
    gerenciaAuditada: "Operaciones",
    descripcion: "Revisión integral de los procesos de distribución y logística",
  },
  {
    id: "AUD-002",
    nombre: "Auditoría Financiera Q1 2024",
    fecha: "2024-02-20",
    gerenciaAuditada: "Finanzas",
    descripcion: "Evaluación de controles financieros y gestión presupuestaria",
  },
  {
    id: "AUD-003",
    nombre: "Auditoría de Seguridad TI",
    fecha: "2024-04-10",
    gerenciaAuditada: "Tecnología",
    descripcion: "Revisión de políticas de seguridad informática y accesos",
  },
  {
    id: "AUD-004",
    nombre: "Auditoría de Gestión de Personal",
    fecha: "2024-01-25",
    gerenciaAuditada: "Recursos Humanos",
    descripcion: "Evaluación de procesos de contratación y capacitación",
  },
  {
    id: "AUD-005",
    nombre: "Auditoría de Cumplimiento Normativo",
    fecha: "2024-05-05",
    gerenciaAuditada: "Operaciones",
    descripcion: "Verificación del cumplimiento de normativas postales",
  },
]

const hoy = new Date()
const formatDate = (date: Date) => date.toISOString().split("T")[0]

export const planesDeAccion: PlanDeAccion[] = [
  {
    id: "PA-001",
    auditoriaId: "AUD-001",
    nombreInforme: "Auditoría de Procesos Operativos 2024",
    fechaInforme: "2024-03-15",
    hallazgo: "Demoras en tiempos de entrega",
    hallazgoDescripcion:
      "Se detectaron demoras significativas en los tiempos de entrega de encomiendas en la zona norte, superando en un 35% los tiempos establecidos en los SLA.",
    criticidad: "alta",
    planAccion: "Implementar sistema de tracking en tiempo real y optimizar rutas de distribución",
    responsablePlan: "María González",
    gerencia: "Operaciones",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 2 * 24 * 60 * 60 * 1000)), // Vence en 2 días
    estadoCumplimiento: "en_implementacion",
    responsableAuditoria: "Ana Martínez",
    evidencias: [
      {
        id: "EV-001",
        nombre: "propuesta_tracking.pdf",
        tipo: "PDF",
        tamaño: "2.4 MB",
        fechaCarga: "2024-06-01",
        cargadoPor: "María González",
      },
    ],
  },
  {
    id: "PA-002",
    auditoriaId: "AUD-001",
    nombreInforme: "Auditoría de Procesos Operativos 2024",
    fechaInforme: "2024-03-15",
    hallazgo: "Falta de capacitación en personal nuevo",
    hallazgoDescripcion:
      "El 40% del personal nuevo no ha completado la capacitación obligatoria en procedimientos operativos.",
    criticidad: "media",
    planAccion: "Desarrollar programa de onboarding estructurado con evaluaciones",
    responsablePlan: "María González",
    gerencia: "Operaciones",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 30 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "pendiente",
    responsableAuditoria: "Ana Martínez",
    evidencias: [],
  },
  {
    id: "PA-003",
    auditoriaId: "AUD-002",
    nombreInforme: "Auditoría Financiera Q1 2024",
    fechaInforme: "2024-02-20",
    hallazgo: "Inconsistencias en conciliaciones bancarias",
    hallazgoDescripcion:
      "Se encontraron diferencias no explicadas en las conciliaciones bancarias del mes de enero por un monto de $15.000.000.",
    criticidad: "alta",
    planAccion: "Revisar y documentar proceso de conciliación, implementar doble verificación",
    responsablePlan: "Carlos Rodríguez",
    gerencia: "Finanzas",
    fechaVencimiento: formatDate(new Date(hoy.getTime() - 10 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "vencido",
    responsableAuditoria: "Pedro Silva",
    evidencias: [
      {
        id: "EV-002",
        nombre: "analisis_diferencias.xlsx",
        tipo: "Excel",
        tamaño: "1.1 MB",
        fechaCarga: "2024-05-15",
        cargadoPor: "Carlos Rodríguez",
      },
    ],
  },
  {
    id: "PA-004",
    auditoriaId: "AUD-002",
    nombreInforme: "Auditoría Financiera Q1 2024",
    fechaInforme: "2024-02-20",
    hallazgo: "Falta de respaldo en gastos menores",
    hallazgoDescripcion: "El 25% de los gastos de caja chica no cuentan con respaldo documental adecuado.",
    criticidad: "baja",
    planAccion: "Implementar sistema digital de rendición de gastos",
    responsablePlan: "Carlos Rodríguez",
    gerencia: "Finanzas",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 45 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "implementado",
    responsableAuditoria: "Pedro Silva",
    evidencias: [
      {
        id: "EV-003",
        nombre: "manual_rendicion.pdf",
        tipo: "PDF",
        tamaño: "3.2 MB",
        fechaCarga: "2024-05-20",
        cargadoPor: "Carlos Rodríguez",
      },
      {
        id: "EV-004",
        nombre: "screenshot_sistema.png",
        tipo: "Imagen",
        tamaño: "856 KB",
        fechaCarga: "2024-05-22",
        cargadoPor: "Carlos Rodríguez",
      },
    ],
  },
  {
    id: "PA-005",
    auditoriaId: "AUD-003",
    nombreInforme: "Auditoría de Seguridad TI",
    fechaInforme: "2024-04-10",
    hallazgo: "Políticas de contraseñas débiles",
    hallazgoDescripcion:
      "Las políticas de contraseñas actuales no cumplen con estándares mínimos de seguridad (longitud, complejidad, rotación).",
    criticidad: "alta",
    planAccion: "Actualizar políticas de contraseñas e implementar autenticación de dos factores",
    responsablePlan: "Laura Soto",
    gerencia: "Tecnología",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 5 * 24 * 60 * 60 * 1000)), // Vence en 5 días
    estadoCumplimiento: "en_implementacion",
    responsableAuditoria: "Ana Martínez",
    evidencias: [
      {
        id: "EV-005",
        nombre: "nueva_politica_pwd.docx",
        tipo: "Word",
        tamaño: "420 KB",
        fechaCarga: "2024-06-05",
        cargadoPor: "Laura Soto",
      },
    ],
  },
  {
    id: "PA-006",
    auditoriaId: "AUD-003",
    nombreInforme: "Auditoría de Seguridad TI",
    fechaInforme: "2024-04-10",
    hallazgo: "Backups sin verificación",
    hallazgoDescripcion:
      "No existe un proceso documentado de verificación de integridad de backups ni pruebas de restauración periódicas.",
    criticidad: "media",
    planAccion: "Establecer cronograma mensual de pruebas de restauración",
    responsablePlan: "Laura Soto",
    gerencia: "Tecnología",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 20 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "pendiente",
    responsableAuditoria: "Ana Martínez",
    evidencias: [],
  },
  {
    id: "PA-007",
    auditoriaId: "AUD-004",
    nombreInforme: "Auditoría de Gestión de Personal",
    fechaInforme: "2024-01-25",
    hallazgo: "Expedientes incompletos",
    hallazgoDescripcion:
      "El 30% de los expedientes de personal no cuenta con toda la documentación requerida por normativa laboral.",
    criticidad: "media",
    planAccion: "Digitalizar expedientes y completar documentación faltante",
    responsablePlan: "Juan Pérez",
    gerencia: "Recursos Humanos",
    fechaVencimiento: formatDate(new Date(hoy.getTime() - 5 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "vencido",
    responsableAuditoria: "Pedro Silva",
    evidencias: [],
  },
  {
    id: "PA-008",
    auditoriaId: "AUD-004",
    nombreInforme: "Auditoría de Gestión de Personal",
    fechaInforme: "2024-01-25",
    hallazgo: "Evaluaciones de desempeño atrasadas",
    hallazgoDescripcion:
      "El 45% de las evaluaciones de desempeño anuales no se han realizado en el período correspondiente.",
    criticidad: "baja",
    planAccion: "Implementar sistema de alertas para evaluaciones pendientes",
    responsablePlan: "Juan Pérez",
    gerencia: "Recursos Humanos",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 60 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "implementado",
    responsableAuditoria: "Pedro Silva",
    evidencias: [
      {
        id: "EV-006",
        nombre: "sistema_alertas.pdf",
        tipo: "PDF",
        tamaño: "1.8 MB",
        fechaCarga: "2024-05-10",
        cargadoPor: "Juan Pérez",
      },
    ],
  },
  {
    id: "PA-009",
    auditoriaId: "AUD-005",
    nombreInforme: "Auditoría de Cumplimiento Normativo",
    fechaInforme: "2024-05-05",
    hallazgo: "Incumplimiento en plazos de respuesta",
    hallazgoDescripcion:
      "Se detectó incumplimiento sistemático en los plazos de respuesta a reclamos establecidos por la normativa postal.",
    criticidad: "alta",
    planAccion: "Reforzar equipo de atención y establecer sistema de escalamiento",
    responsablePlan: "María González",
    gerencia: "Operaciones",
    fechaVencimiento: formatDate(new Date(hoy.getTime() - 2 * 24 * 60 * 60 * 1000)), // Vencido hace 2 días
    estadoCumplimiento: "vencido",
    responsableAuditoria: "Ana Martínez",
    evidencias: [],
  },
  {
    id: "PA-010",
    auditoriaId: "AUD-005",
    nombreInforme: "Auditoría de Cumplimiento Normativo",
    fechaInforme: "2024-05-05",
    hallazgo: "Registros de entrega incompletos",
    hallazgoDescripcion:
      "Los registros de entrega no incluyen todos los campos requeridos por la normativa de trazabilidad.",
    criticidad: "media",
    planAccion: "Actualizar formularios de entrega y capacitar al personal",
    responsablePlan: "María González",
    gerencia: "Operaciones",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 25 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "en_implementacion",
    responsableAuditoria: "Ana Martínez",
    evidencias: [
      {
        id: "EV-007",
        nombre: "nuevo_formulario.pdf",
        tipo: "PDF",
        tamaño: "560 KB",
        fechaCarga: "2024-06-08",
        cargadoPor: "María González",
      },
    ],
  },
  {
    id: "PA-011",
    auditoriaId: "AUD-001",
    nombreInforme: "Auditoría de Procesos Operativos 2024",
    fechaInforme: "2024-03-15",
    hallazgo: "Falta de estandarización en procesos de clasificación",
    hallazgoDescripcion:
      "Existen variaciones significativas en los procesos de clasificación entre diferentes centros de distribución.",
    criticidad: "media",
    planAccion: "Desarrollar manual de procedimientos estandarizados y capacitación",
    responsablePlan: "María González",
    gerencia: "Operaciones",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 40 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "pendiente",
    responsableAuditoria: "Ana Martínez",
    evidencias: [],
  },
  {
    id: "PA-012",
    auditoriaId: "AUD-002",
    nombreInforme: "Auditoría Financiera Q1 2024",
    fechaInforme: "2024-02-20",
    hallazgo: "Retrasos en reportes financieros mensuales",
    hallazgoDescripcion:
      "Los reportes financieros mensuales se están entregando con un promedio de 5 días de retraso respecto a las fechas comprometidas.",
    criticidad: "baja",
    planAccion: "Automatizar procesos de consolidación y establecer alertas",
    responsablePlan: "Carlos Rodríguez",
    gerencia: "Finanzas",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 35 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "en_implementacion",
    responsableAuditoria: "Pedro Silva",
    evidencias: [
      {
        id: "EV-008",
        nombre: "automatizacion_reportes.pdf",
        tipo: "PDF",
        tamaño: "1.5 MB",
        fechaCarga: "2024-06-10",
        cargadoPor: "Carlos Rodríguez",
      },
    ],
  },
  {
    id: "PA-013",
    auditoriaId: "AUD-003",
    nombreInforme: "Auditoría de Seguridad TI",
    fechaInforme: "2024-04-10",
    hallazgo: "Falta de monitoreo de accesos privilegiados",
    hallazgoDescripcion:
      "No existe un sistema de monitoreo y alertas para accesos privilegiados a sistemas críticos.",
    criticidad: "alta",
    planAccion: "Implementar sistema de monitoreo de accesos y auditoría de privilegios",
    responsablePlan: "Laura Soto",
    gerencia: "Tecnología",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 15 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "en_implementacion",
    responsableAuditoria: "Ana Martínez",
    evidencias: [
      {
        id: "EV-009",
        nombre: "propuesta_monitoreo.docx",
        tipo: "Word",
        tamaño: "890 KB",
        fechaCarga: "2024-06-12",
        cargadoPor: "Laura Soto",
      },
    ],
  },
  {
    id: "PA-014",
    auditoriaId: "AUD-004",
    nombreInforme: "Auditoría de Gestión de Personal",
    fechaInforme: "2024-01-25",
    hallazgo: "Falta de plan de sucesión en cargos clave",
    hallazgoDescripcion:
      "No existe documentación ni planificación de sucesión para cargos gerenciales y de supervisión.",
    criticidad: "media",
    planAccion: "Desarrollar plan de sucesión y programa de desarrollo de talentos",
    responsablePlan: "Juan Pérez",
    gerencia: "Recursos Humanos",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 50 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "pendiente",
    responsableAuditoria: "Pedro Silva",
    evidencias: [],
  },
  {
    id: "PA-015",
    auditoriaId: "AUD-005",
    nombreInforme: "Auditoría de Cumplimiento Normativo",
    fechaInforme: "2024-05-05",
    hallazgo: "Falta de registro de capacitaciones en normativa postal",
    hallazgoDescripcion:
      "No se mantiene un registro centralizado de las capacitaciones realizadas al personal sobre normativa postal vigente.",
    criticidad: "baja",
    planAccion: "Implementar sistema de registro y seguimiento de capacitaciones",
    responsablePlan: "María González",
    gerencia: "Operaciones",
    fechaVencimiento: formatDate(new Date(hoy.getTime() + 30 * 24 * 60 * 60 * 1000)),
    estadoCumplimiento: "implementado",
    responsableAuditoria: "Ana Martínez",
    evidencias: [
      {
        id: "EV-010",
        nombre: "sistema_registro.pdf",
        tipo: "PDF",
        tamaño: "2.1 MB",
        fechaCarga: "2024-05-28",
        cargadoPor: "María González",
      },
      {
        id: "EV-011",
        nombre: "manual_uso.pdf",
        tipo: "PDF",
        tamaño: "1.3 MB",
        fechaCarga: "2024-06-01",
        cargadoPor: "María González",
      },
    ],
  },
]

export const actividadesSeguimiento: ActividadSeguimiento[] = [
  {
    id: "ACT-001",
    planId: "PA-001",
    fecha: "2024-05-15",
    usuario: "María González",
    rol: "gerencia",
    accion: "Cargó evidencia: propuesta_tracking.pdf",
    comentario: "Propuesta inicial del sistema de tracking",
  },
  {
    id: "ACT-002",
    planId: "PA-001",
    fecha: "2024-05-20",
    usuario: "Ana Martínez",
    rol: "auditor",
    accion: "Revisó avance",
    comentario: "Propuesta aprobada, pendiente implementación",
  },
  {
    id: "ACT-003",
    planId: "PA-001",
    fecha: "2024-06-01",
    usuario: "María González",
    rol: "gerencia",
    accion: "Actualizó estado a En Implementación",
  },
  {
    id: "ACT-004",
    planId: "PA-003",
    fecha: "2024-05-10",
    usuario: "Carlos Rodríguez",
    rol: "gerencia",
    accion: "Cargó evidencia: analisis_diferencias.xlsx",
  },
  {
    id: "ACT-005",
    planId: "PA-003",
    fecha: "2024-05-25",
    usuario: "Pedro Silva",
    rol: "auditor",
    accion: "Marcó como Observado",
    comentario: "Falta documentar proceso de doble verificación",
  },
  {
    id: "ACT-006",
    planId: "PA-004",
    fecha: "2024-05-20",
    usuario: "Carlos Rodríguez",
    rol: "gerencia",
    accion: "Cargó evidencias del sistema implementado",
  },
  {
    id: "ACT-007",
    planId: "PA-004",
    fecha: "2024-05-28",
    usuario: "Pedro Silva",
    rol: "auditor",
    accion: "Validó implementación",
    comentario: "Sistema funcionando correctamente",
  },
  {
    id: "ACT-008",
    planId: "PA-005",
    fecha: "2024-06-01",
    usuario: "Laura Soto",
    rol: "gerencia",
    accion: "Cargó nueva política de contraseñas",
  },
  {
    id: "ACT-009",
    planId: "PA-005",
    fecha: "2024-06-05",
    usuario: "Laura Soto",
    rol: "gerencia",
    accion: "Actualizó estado a En Implementación",
    comentario: "Iniciando despliegue de 2FA",
  },
  {
    id: "ACT-010",
    planId: "PA-008",
    fecha: "2024-05-08",
    usuario: "Juan Pérez",
    rol: "gerencia",
    accion: "Implementó sistema de alertas",
  },
  {
    id: "ACT-011",
    planId: "PA-008",
    fecha: "2024-05-15",
    usuario: "Pedro Silva",
    rol: "auditor",
    accion: "Validó implementación",
    comentario: "Sistema de alertas operativo",
  },
  {
    id: "ACT-012",
    planId: "PA-012",
    fecha: "2024-06-05",
    usuario: "Carlos Rodríguez",
    rol: "gerencia",
    accion: "Inició proceso de automatización",
    comentario: "Comenzando desarrollo de scripts de consolidación",
  },
  {
    id: "ACT-013",
    planId: "PA-012",
    fecha: "2024-06-10",
    usuario: "Carlos Rodríguez",
    rol: "gerencia",
    accion: "Cargó evidencia: automatizacion_reportes.pdf",
  },
  {
    id: "ACT-014",
    planId: "PA-013",
    fecha: "2024-06-08",
    usuario: "Laura Soto",
    rol: "gerencia",
    accion: "Inició evaluación de proveedores",
    comentario: "Revisando opciones de sistemas de monitoreo",
  },
  {
    id: "ACT-015",
    planId: "PA-013",
    fecha: "2024-06-12",
    usuario: "Laura Soto",
    rol: "gerencia",
    accion: "Cargó propuesta de monitoreo",
  },
  {
    id: "ACT-016",
    planId: "PA-015",
    fecha: "2024-05-25",
    usuario: "María González",
    rol: "gerencia",
    accion: "Implementó sistema de registro",
  },
  {
    id: "ACT-017",
    planId: "PA-015",
    fecha: "2024-05-28",
    usuario: "María González",
    rol: "gerencia",
    accion: "Cargó documentación del sistema",
  },
  {
    id: "ACT-018",
    planId: "PA-015",
    fecha: "2024-06-01",
    usuario: "María González",
    rol: "gerencia",
    accion: "Cargó manual de uso",
  },
  {
    id: "ACT-019",
    planId: "PA-015",
    fecha: "2024-06-05",
    usuario: "Ana Martínez",
    rol: "auditor",
    accion: "Validó implementación",
    comentario: "Sistema funcionando correctamente, plan completado",
  },
]

export const gerencias = ["Operaciones", "Finanzas", "Tecnología", "Recursos Humanos"]

export const estadosLabels: Record<EstadoCumplimiento, string> = {
  pendiente: "Pendiente",
  en_implementacion: "En Implementación",
  implementado: "Implementado",
  vencido: "Vencido",
}

export const criticidadLabels: Record<Criticidad, string> = {
  alta: "Alta",
  media: "Media",
  baja: "Baja",
}
